
services:
  app:
    image: api-smart-order
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    entrypoint: sh -c 'npm install && npm run start:swc' && echo "API is running on port ${PORT}"
    depends_on:
      - db
      # - mongodb
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
    environment:
      - ENV_VAR_NAME=value
    networks:
      - app-network
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
  # mongodb:
  #   image: mongo:latest
  #   environment:
  #     - MONGO_HOST=${MONGO_HOST}
  #     - MONGO_PORT=${MONGO_PORT}
  #     - MONGO_DB_NAME=${MONGO_DB_NAME}
  #     - MONGO_USER=${MONGO_USER}
  #     - MONGO_PASSWORD=${MONGO_PASSWORD}
  #   networks:
  #     - app-network
volumes:
  db-data:
networks:
  app-network:
    driver: bridge
